/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f8f9ff",
        "inverse-primary": "#b0c6ff",
        "on-surface": "#0b1c30",
        "secondary-fixed": "#dde1ff",
        "primary": "#001f51",
        "surface-tint": "#395ca6",
        "on-primary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "primary-container": "#00337c",
        "on-primary-fixed-variant": "#1c448c",
        "secondary-container": "#708cfd",
        "surface-variant": "#d3e4fe",
        "surface-container-highest": "#d3e4fe",
        "surface-container-low": "#eff4ff",
        "on-surface-variant": "#434651",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#173bab",
        "on-tertiary-container": "#9ca1a5",
        "surface-dim": "#cbdbf5",
        "secondary": "#3755c3",
        "primary-fixed": "#d9e2ff",
        "on-secondary-container": "#00217a",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "outline-variant": "#c4c6d3",
        "primary-fixed-dim": "#b0c6ff",
        "background": "#f8f9ff",
        "outline": "#747782",
        "inverse-surface": "#213145",
        "tertiary-container": "#33383b",
        "secondary-fixed-dim": "#b8c4ff",
        "error": "#ba1a1a",
        "surface-container": "#e5eeff",
        "on-secondary-fixed": "#001453",
        "on-background": "#0b1c30",
        "on-error-container": "#93000a",
        "on-primary-container": "#7d9fee",
        "surface": "#f8f9ff",
        "on-primary-fixed": "#001945",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "success": "#1a6e3c",
        "success-container": "#d4f5e2",
        "on-success-container": "#003919",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        margin: "32px",
        unit: "4px",
        gutter: "24px",
        "container-max": "1440px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["Space Grotesk", "monospace"],
      },
      fontSize: {
        "data-display": ["40px", { lineHeight: "1.0", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-xl": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}